[supervisord]
nodaemon=true

[program:celery]
command=poetry run celery -A app.celery_app worker --loglevel=debug
autostart=true
autorestart=true
stderr_logfile=/app/logs/celery.err.log
stdout_logfile=/app/logs/celery.out.log


[program:gunicorn]
command=poetry run gunicorn --bind :8787 -k uvicorn.workers.UvicornH11Worker --workers 4 app.main:app
autostart=true
autorestart=true
stderr_logfile=/app/logs/gunicorn.err.log
stdout_logfile=/app/logs/gunicorn.out.log
