"""add brand field

Revision ID: 0a198716f6c8
Revises: 91efe6c3eaed
Create Date: 2025-07-16 16:29:31.693396

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0a198716f6c8'
down_revision = '91efe6c3eaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
