"""fix operations table

Revision ID: 26587ae2a6f7
Revises: c674fd5537f6
Create Date: 2025-05-07 14:31:27.830356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '26587ae2a6f7'
down_revision = 'c674fd5537f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'warehouse_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('operation', 'is_automatic')
    
    # Обновляем перечисление operationtype
    op.execute("ALTER TYPE operationtype RENAME TO operationtype_old")
    op.execute("CREATE TYPE operationtype AS ENUM ('stock_in', 'stock_in_file', 'stock_out_order', 'stock_out_manual', 'transfer', 'transfer_file', 'product_create', 'product_delete')")
    op.execute("ALTER TABLE operation ALTER COLUMN operation_type TYPE operationtype USING operation_type::text::operationtype")
    op.execute("DROP TYPE operationtype_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('is_automatic', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('operation', 'warehouse_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # Возвращаем старое перечисление
    op.execute("ALTER TYPE operationtype RENAME TO operationtype_new")
    op.execute("CREATE TYPE operationtype AS ENUM ('STOCK_IN', 'STOCK_IN_BULK', 'STOCK_OUT_ORDER', 'STOCK_OUT_MANUAL', 'TRANSFER', 'TRANSFER_BULK')")
    op.execute("ALTER TABLE operation ALTER COLUMN operation_type TYPE operationtype USING operation_type::text::operationtype")
    op.execute("DROP TYPE operationtype_new")
    # ### end Alembic commands ###
