"""add first_publication_date field to product

Revision ID: 3253e5c2cb12
Revises: ae2f3d4c5b6
Create Date: 2025-08-19 11:33:07.279538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3253e5c2cb12'
down_revision = 'ae2f3d4c5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('first_publication_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_product_first_publication_date'), 'product', ['first_publication_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_first_publication_date'), table_name='product')
    op.drop_column('product', 'first_publication_date')
    # ### end Alembic commands ###
