"""проверка состояния

Revision ID: 356ead686a7c
Revises: 7b29820f8dca
Create Date: 2025-08-06 10:12:21.644840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '356ead686a7c'
down_revision = '7b29820f8dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
