"""delete flag sync from product

Revision ID: 35b3dcc0c228
Revises: bb70db3c2750
Create Date: 2025-07-17 15:49:35.756742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '35b3dcc0c228'
down_revision = 'bb70db3c2750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_sync_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_sync_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
