"""add_cascade_constraints_to_warehouse_tables

Revision ID: 35ee93120cf9
Revises: fb2869710b96
Create Date: 2025-06-20 12:05:49.612938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '35ee93120cf9'
down_revision = 'fb2869710b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('sale_sku_fkey', 'sale', type_='foreignkey')
    op.create_foreign_key(None, 'sale', 'product', ['sku'], ['sku'], ondelete='CASCADE')
    op.drop_constraint('stock_sku_fkey', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'product', ['sku'], ['sku'], ondelete='CASCADE')
    op.alter_column('transfer', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('transfer_sku_fkey', 'transfer', type_='foreignkey')
    op.create_foreign_key(None, 'transfer', 'product', ['sku'], ['sku'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.create_foreign_key('transfer_sku_fkey', 'transfer', 'product', ['sku'], ['sku'])
    op.alter_column('transfer', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_sku_fkey', 'stock', 'product', ['sku'], ['sku'])
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.create_foreign_key('sale_sku_fkey', 'sale', 'product', ['sku'], ['sku'])
    op.alter_column('sale', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
