"""fix

Revision ID: 3ba03157786d
Revises: 7db852e0cc29
Create Date: 2025-03-23 19:00:33.963279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3ba03157786d'
down_revision = '7db852e0cc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allegro_orders', sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'allegro_orders', 'allegro_tokens', ['token_id'], ['id_'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allegro_orders', type_='foreignkey')
    op.drop_column('allegro_orders', 'token_id')
    # ### end Alembic commands ###
