"""add name_eng to product"

Revision ID: 4c75bc98e512
Revises: 3253e5c2cb12
Create Date: 2025-08-19 13:48:26.120809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4c75bc98e512'
down_revision = '3253e5c2cb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name_eng', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'name_eng')
    # ### end Alembic commands ###
