"""account name unique

Revision ID: 50cdd90859e7
Revises: 35b3dcc0c228
Create Date: 2025-07-17 16:08:14.844135

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '50cdd90859e7'
down_revision = '35b3dcc0c228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'allegro_tokens', ['account_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allegro_tokens', type_='unique')
    # ### end Alembic commands ###
