"""change operation

Revision ID: 5fb988fda8d2
Revises: 9f24a95e0dd4
Create Date: 2025-08-11 16:40:20.205217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb988fda8d2'
down_revision = '9f24a95e0dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_stock_operations', sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('pending_stock_operations', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_pending_stock_operations_account_name'), 'pending_stock_operations', ['account_name'], unique=False)
    op.drop_column('pending_stock_operations', 'max_retries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_stock_operations', sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pending_stock_operations_account_name'), table_name='pending_stock_operations')
    op.alter_column('pending_stock_operations', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('pending_stock_operations', 'account_name')
    # ### end Alembic commands ###
