"""try fix

Revision ID: 6829a1f9bfaf
Revises: 26587ae2a6f7
Create Date: 2025-05-07 17:05:26.309722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6829a1f9bfaf'
down_revision = '26587ae2a6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Конвертируем перечисление в VARCHAR
    op.execute("ALTER TABLE operation ALTER COLUMN operation_type TYPE VARCHAR USING operation_type::text")
    op.execute("DROP TYPE operationtype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем перечисление
    op.execute("CREATE TYPE operationtype AS ENUM ('stock_in', 'stock_in_file', 'stock_out_order', 'stock_out_manual', 'transfer', 'transfer_file', 'product_create', 'product_delete')")
    op.execute("ALTER TABLE operation ALTER COLUMN operation_type TYPE operationtype USING operation_type::operationtype")
    # ### end Alembic commands ###
