"""change eans to jsonB

Revision ID: 7a26a831795f
Revises: c77fa904f0df
Create Date: 2025-04-21 16:38:40.975506

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7a26a831795f'
down_revision = 'c77fa904f0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
