"""added false default price sync

Revision ID: 7b29820f8dca
Revises: ac7fca070b63
Create Date: 2025-08-03 14:31:33.851806

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7b29820f8dca'
down_revision = 'ac7fca070b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
