"""fixed

Revision ID: 7db852e0cc29
Revises: 6800ccaf0482
Create Date: 2025-03-23 09:23:26.411181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7db852e0cc29'
down_revision = '6800ccaf0482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
