"""added is_sync_enabled field for product

Revision ID: 8b3c770e2017
Revises: ab5ee04c06de
Create Date: 2025-07-16 15:16:06.458614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b3c770e2017'
down_revision = 'ab5ee04c06de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_sync_enabled', sa.Boolean(), nullable=True))
    op.execute('UPDATE product SET is_sync_enabled = FALSE')
    op.alter_column('product', 'is_sync_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_sync_enabled')
    # ### end Alembic commands ###
