"""create lock table

Revision ID: 91efe6c3eaed
Revises: 8b3c770e2017
Create Date: 2025-07-16 16:17:06.594809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '91efe6c3eaed'
down_revision = '8b3c770e2017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
