"""update

Revision ID: 9d08ac146c2c
Revises: e4657ade323c
Create Date: 2025-08-06 11:33:54.485268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9d08ac146c2c'
down_revision = 'e4657ade323c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pending_stock_operations_token_id_fkey'), 'pending_stock_operations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('pending_stock_operations_token_id_fkey'), 'pending_stock_operations', 'allegro_tokens', ['token_id'], ['id_'])
    # ### end Alembic commands ###
