"""delete sku and quantity and add line_items to pending stock operations"

Revision ID: 9f24a95e0dd4
Revises: c5d637229ac1
Create Date: 2025-08-11 14:11:35.400768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f24a95e0dd4'
down_revision = 'c5d637229ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_stock_operations', sa.Column('line_items', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_pending_stock_operations_sku'), table_name='pending_stock_operations')
    op.drop_column('pending_stock_operations', 'quantity')
    op.drop_column('pending_stock_operations', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_stock_operations', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pending_stock_operations', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pending_stock_operations_sku'), 'pending_stock_operations', ['sku'], unique=False)
    op.drop_column('pending_stock_operations', 'line_items')
    # ### end Alembic commands ###
