"""add_original_image_and_url_fields

Revision ID: ac7fca070b63
Revises: 50cdd90859e7
Create Date: 2025-08-03 11:12:45.884998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ac7fca070b63'
down_revision = '50cdd90859e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('original_image', sa.LargeBinary(), nullable=True))
    op.add_column('product', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_url')
    op.drop_column('product', 'original_image')
    # ### end Alembic commands ###
