"""added fields for PendingStockOperation

Revision ID: af835ec1d35a
Revises: b5f1fb88dfa9
Create Date: 2025-08-16 10:42:40.912966

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'af835ec1d35a'
down_revision = 'b5f1fb88dfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_stock_operations', sa.Column('line_items_loaded_at', sa.DateTime(), nullable=True))
    op.add_column('pending_stock_operations', sa.Column('stock_deducted_at', sa.DateTime(), nullable=True))
    op.add_column('pending_stock_operations', sa.Column('microservice_synced_at', sa.DateTime(), nullable=True))
    op.add_column('pending_stock_operations', sa.Column('cancelled_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pending_stock_operations', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pending_stock_operations', sa.Column('rollback_operations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_stock_operations', 'rollback_operations')
    op.drop_column('pending_stock_operations', 'cancellation_reason')
    op.drop_column('pending_stock_operations', 'cancelled_by')
    op.drop_column('pending_stock_operations', 'microservice_synced_at')
    op.drop_column('pending_stock_operations', 'stock_deducted_at')
    op.drop_column('pending_stock_operations', 'line_items_loaded_at')
    # ### end Alembic commands ###
