"""add_product_allegro_sync_settings_table

Revision ID: bb70db3c2750
Revises: cc57605600d4
Create Date: 2025-07-17 14:09:45.371523

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bb70db3c2750'
down_revision = 'cc57605600d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_allegro_sync_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allegro_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_multiplier', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_stock_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku'], ['product.sku'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_sku', 'allegro_account_name', name='_product_account_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_allegro_sync_settings')
    # ### end Alembic commands ###
