"""set constraint on order id pending operation

Revision ID: c275a8dcee89
Revises: 5fb988fda8d2
Create Date: 2025-08-13 10:14:47.174554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c275a8dcee89'
down_revision = '5fb988fda8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pending_stock_operations_token_order', 'pending_stock_operations', ['token_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pending_stock_operations_token_order', 'pending_stock_operations', type_='unique')
    # ### end Alembic commands ###
