"""fix order

Revision ID: c533cd0c2a56
Revises: 3ba03157786d
Create Date: 2025-03-24 20:11:12.578099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c533cd0c2a56'
down_revision = '3ba03157786d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
