"""OrderNotificationTracker

Revision ID: c5d637229ac1
Revises: d74466df3ff5
Create Date: 2025-08-11 10:22:26.267964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c5d637229ac1'
down_revision = 'd74466df3ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_notification_tracker',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validation_failure_notified', sa.Boolean(), nullable=False),
    sa.Column('max_retries_notified', sa.Boolean(), nullable=False),
    sa.Column('last_notification_at', sa.DateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('suppression_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_notification_tracker_created_at'), 'order_notification_tracker', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_notification_tracker_order_id'), 'order_notification_tracker', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_notification_tracker_token_id'), 'order_notification_tracker', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_notification_tracker_token_id'), table_name='order_notification_tracker')
    op.drop_index(op.f('ix_order_notification_tracker_order_id'), table_name='order_notification_tracker')
    op.drop_index(op.f('ix_order_notification_tracker_created_at'), table_name='order_notification_tracker')
    op.drop_table('order_notification_tracker')
    # ### end Alembic commands ###
