"""added operations

Revision ID: c674fd5537f6
Revises: 48f2d27c6e8f
Create Date: 2025-05-06 21:02:10.357004

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c674fd5537f6'
down_revision = '48f2d27c6e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('STOCK_IN', 'STOCK_IN_BULK', 'STOCK_OUT_ORDER', 'STOCK_OUT_MANUAL', 'TRANSFER', 'TRANSFER_BULK', name='operationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('products_data', sa.JSON(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
