"""add new field to allegro order

Revision ID: d1a2506011c6
Revises: 988d6c9b7afa
Create Date: 2025-04-21 18:46:30.914677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd1a2506011c6'
down_revision = '988d6c9b7afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allegro_orders', sa.Column('is_stock_updated', sa.Boolean(), nullable=False, server_default='false'))
    
    # Устанавливаем значение False для всех существующих записей
    op.execute("UPDATE allegro_orders SET is_stock_updated = false WHERE is_stock_updated IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allegro_orders', 'is_stock_updated')
    # ### end Alembic commands ###
