"""add_stock_synchronization_tables

Revision ID: e4657ade323c
Revises: 356ead686a7c
Create Date: 2025-08-06 11:30:50.112059

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e4657ade323c'
down_revision = '356ead686a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_stock_operations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation_type', sa.Enum('DEDUCTION', 'REFUND', 'ADJUSTMENT', name='operationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allegro_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['allegro_order_id'], ['allegro_orders.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['allegro_tokens.id_'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_stock_operations_created_at'), 'pending_stock_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_stock_operations_next_retry_at'), 'pending_stock_operations', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_pending_stock_operations_order_id'), 'pending_stock_operations', ['order_id'], unique=False)
    op.create_index(op.f('ix_pending_stock_operations_sku'), 'pending_stock_operations', ['sku'], unique=False)
    op.create_index(op.f('ix_pending_stock_operations_status'), 'pending_stock_operations', ['status'], unique=False)
    op.create_index(op.f('ix_pending_stock_operations_token_id'), 'pending_stock_operations', ['token_id'], unique=False)
    op.create_table('stock_synchronization_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('operation_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['pending_stock_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_synchronization_logs_action'), 'stock_synchronization_logs', ['action'], unique=False)
    op.create_index(op.f('ix_stock_synchronization_logs_operation_id'), 'stock_synchronization_logs', ['operation_id'], unique=False)
    op.create_index(op.f('ix_stock_synchronization_logs_timestamp'), 'stock_synchronization_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_synchronization_logs_timestamp'), table_name='stock_synchronization_logs')
    op.drop_index(op.f('ix_stock_synchronization_logs_operation_id'), table_name='stock_synchronization_logs')
    op.drop_index(op.f('ix_stock_synchronization_logs_action'), table_name='stock_synchronization_logs')
    op.drop_table('stock_synchronization_logs')
    op.drop_index(op.f('ix_pending_stock_operations_token_id'), table_name='pending_stock_operations')
    op.drop_index(op.f('ix_pending_stock_operations_status'), table_name='pending_stock_operations')
    op.drop_index(op.f('ix_pending_stock_operations_sku'), table_name='pending_stock_operations')
    op.drop_index(op.f('ix_pending_stock_operations_order_id'), table_name='pending_stock_operations')
    op.drop_index(op.f('ix_pending_stock_operations_next_retry_at'), table_name='pending_stock_operations')
    op.drop_index(op.f('ix_pending_stock_operations_created_at'), table_name='pending_stock_operations')
    op.drop_table('pending_stock_operations')
    # ### end Alembic commands ###
