"""try fix

Revision ID: e5cc3cb068cf
Revises: 6829a1f9bfaf
Create Date: 2025-05-07 17:16:41.988970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5cc3cb068cf'
down_revision = '6829a1f9bfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'operation_type',
               existing_type=postgresql.ENUM('STOCK_IN', 'STOCK_IN_BULK', 'STOCK_OUT_ORDER', 'STOCK_OUT_MANUAL', 'TRANSFER', 'TRANSFER_BULK', name='operationtype'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'operation_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('STOCK_IN', 'STOCK_IN_BULK', 'STOCK_OUT_ORDER', 'STOCK_OUT_MANUAL', 'TRANSFER', 'TRANSFER_BULK', name='operationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
